#
# txtai Material for MkDocs configuration
#

site_name: txtai
site_description: "txtai: Build AI-powered semantic search applications"
repo_name: neuml/txtai
repo_url: https://github.com/neuml/txtai
copyright: © NeuML LLC, Apache-2.0 License
theme:
    name: material
    logo: images/logo.png
    favicon: images/logo.png
    icon:
        repo: fontawesome/brands/github
    palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    features:
        - navigation.indexes
        - navigation.instant
plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                rendering:
                    show_root_full_path: false
                    show_root_heading: true
                    show_root_toc_entry: false
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
nav:
    - Home: index.md
    - Why txtai?: why.md
    - Installation: install.md
    - Examples: examples.md
    - Embeddings:
        - embeddings/index.md
        - Configuration: embeddings/configuration.md
        - Methods: embeddings/methods.md
        - Query Guide: embeddings/query.md
    - Pipeline:
        - pipeline/index.md
        - Audio:
            - Transcription: pipeline/audio/transcription.md
        - Data:
            - Segmentation: pipeline/data/segmentation.md
            - Tabular: pipeline/data/tabular.md
            - Textractor: pipeline/data/textractor.md
        - Image:
            - Caption: pipeline/image/caption.md
            - Objects: pipeline/image/objects.md
        - Text:
            - Extractor: pipeline/text/extractor.md
            - Labels: pipeline/text/labels.md
            - Similarity: pipeline/text/similarity.md
            - Summary: pipeline/text/summary.md
            - Translation: pipeline/text/translation.md
        - Train:
            - HF ONNX: pipeline/train/hfonnx.md
            - ML ONNX: pipeline/train/mlonnx.md
            - Trainer: pipeline/train/trainer.md
    - Workflow:
        - workflow/index.md
        - Task: workflow/task.md
        - File: workflow/file.md
        - Image: workflow/image.md
        - Retrieve: workflow/retrieve.md
        - Service: workflow/service.md
        - Storage: workflow/storage.md
        - Url: workflow/url.md
        - Workflow: workflow/workflow.md
    - API:
        - api/index.md
        - Configuration: api/configuration.md
        - Cluster: api/cluster.md
        - Docker: api/docker.md
    - Further Reading: articles.md
